global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using AoC.Common;
global using static AoC.Common.SantaHelper;
global using System.Threading;
global using System.Collections.Concurrent;
global using System.Security.Cryptography;
global using System.Text.RegularExpressions;